using CapaDapper.Cadena;
using CapaDapper.DataService;
using CapaDapper.Dtos;
using Microsoft.AspNetCore.Connections;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace BackFabrica.Controllers
{
    /// <summary>
    /// Provides schema-driven CRUD endpoints that operate against any table in any registered database.
    /// The client passes the full <see cref="DbSchema"/> JSON (generated by <c>SchemaController</c>)
    /// alongside the data payload, allowing the server to build and execute parameterized SQL
    /// without hard-coded entity mappings.
    /// </summary>
    [Route("api/[controller]")]
    [ApiController]
    public class DynamicCrudController : ControllerBase
    {
        private readonly DynamicCrudService _dynamicService;
        private readonly IConfiguration _configuration;
        private readonly IDbConnectionFactory _connectionFactory;
        private readonly IDatabaseContext _dbContext;

        public DynamicCrudController(DynamicCrudService dynamicService, IConfiguration configuration, IDbConnectionFactory connectionFactory, IDatabaseContext dbContext)
        {
            _dynamicService = dynamicService;
            _configuration = configuration;
            _connectionFactory = connectionFactory;
            _dbContext = dbContext;
        }

        /// <summary>
        /// Converts <see cref="JsonElement"/> values in a data dictionary to their native .NET types.
        /// String values that match the ISO 8601 date format are converted to <see cref="DateTime"/>.
        /// </summary>
        private Dictionary<string, object> ConvertJsonElementsToNetTypes(Dictionary<string, object> data)
        {
            if (data == null) return null;

            var result = new Dictionary<string, object>();
            foreach (var kvp in data)
            {
                if (kvp.Value is JsonElement element)
                {
                    result[kvp.Key] = ConvertJsonElement(element);
                }
                else
                {
                    result[kvp.Key] = kvp.Value;
                }
            }
            return result;
        }

        private object ConvertJsonElement(JsonElement element)
        {
            switch (element.ValueKind)
            {
                case JsonValueKind.String:
                    string stringValue = element.GetString();
                    // Attempt to parse ISO 8601 date strings.
                    if (DateTime.TryParse(stringValue, null, System.Globalization.DateTimeStyles.RoundtripKind, out DateTime dateValue))
                    {
                        return dateValue;
                    }
                    return stringValue;
                case JsonValueKind.Number:
                    if (element.TryGetInt32(out int intValue))
                        return intValue;
                    if (element.TryGetInt64(out long longValue))
                        return longValue;
                    if (element.TryGetDouble(out double doubleValue))
                        return doubleValue;
                    return element.GetDecimal();
                case JsonValueKind.True:
                    return true;
                case JsonValueKind.False:
                    return false;
                case JsonValueKind.Null:
                case JsonValueKind.Undefined:
                    return null;
                default:
                    return element.ToString();
            }
        }

        /// <summary>
        /// Validates the incoming data dictionary against the schema for the given table,
        /// resolving both exact-case and snake_case column name variants.
        /// Unrecognised keys are silently dropped.
        /// </summary>
        private Dictionary<string, object> ValidateAndMapData(Dictionary<string, object> data, string tableName, DbSchema schema)
        {
            if (data == null || schema?.Columns == null) return data;

            var columnMap = schema.Columns
                .Where(c => c.Table.Equals(tableName, StringComparison.OrdinalIgnoreCase))
                .ToDictionary(
                    c => c.Name,
                    c => c.Name,
                    StringComparer.OrdinalIgnoreCase
                );

            var validatedData = new Dictionary<string, object>();

            foreach (var kvp in data)
            {
                string dataKey = kvp.Key;

                if (columnMap.TryGetValue(dataKey, out string realColumnName))
                {
                    validatedData[realColumnName] = kvp.Value;
                }
                else
                {
                    string snakeCaseKey = ConvertToSnakeCase(dataKey);
                    if (columnMap.TryGetValue(snakeCaseKey, out string realColumnNameSnake))
                    {
                        validatedData[realColumnNameSnake] = kvp.Value;
                    }
                }
            }

            return validatedData;
        }

        /// <summary>
        /// Converts a PascalCase or camelCase identifier to snake_case.
        /// </summary>
        private string ConvertToSnakeCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;

            return string.Concat(
                input.Select((x, i) => i > 0 && char.IsUpper(x)
                    ? "_" + x.ToString()
                    : x.ToString())
            ).ToLower();
        }

        /// <summary>
        /// Inserts a new row into the specified table using the schema and data provided in the request body.
        /// The schema must include a valid <c>database_name</c> property.
        /// </summary>
        /// <param name="tableName">Name of the target table.</param>
        /// <param name="request">Request payload containing the schema definition and the field values to insert.</param>
        [HttpPost("V2/CREADTE")]
        public async Task<IActionResult> Create(string tableName, [FromBody] DynamicRequestDto request)
        {
            try
            {
                if (request.Schema == null)
                    return BadRequest("El esquema es obligatorio.");

                if (string.IsNullOrEmpty(request.Schema.DatabaseName))
                    return BadRequest("El JSON del esquema no contiene la propiedad 'database_name'.");

                _dbContext.CurrentDb = request.Schema.DatabaseName;

                var convertedData = ConvertJsonElementsToNetTypes(request.Data);

                var validatedData = ValidateAndMapData(convertedData, tableName, request.Schema);

                if (validatedData.Count == 0)
                    return BadRequest("No hay datos válidos para insertar.");

                using (var connection = _connectionFactory.CreateConnection())
                {
                    var result = await _dynamicService.InsertDynamicAsync(
                        tableName,
                        validatedData,
                        request.Schema,
                        connection.ConnectionString
                    );

                    return Ok(new { message = "Registro creado exitosamente", rowsAffected = result });
                }
            }
            catch (Exception ex)
            {
                return BadRequest(new { error = ex.Message });
            }
        }

        /// <summary>
        /// Updates an existing row in the specified table using the schema and data provided in the request body.
        /// The schema must include a valid <c>database_name</c> property.
        /// </summary>
        /// <param name="tableName">Name of the target table.</param>
        /// <param name="request">Request payload containing the schema definition and the updated field values.</param>
        [HttpPost("V2/UPDATE")]
        public async Task<IActionResult> Update(string tableName, [FromBody] DynamicRequestDto request)
        {
            try
            {
                if (request.Schema == null)
                    return BadRequest("El esquema es obligatorio.");

                if (string.IsNullOrEmpty(request.Schema.DatabaseName))
                    return BadRequest("El JSON del esquema no contiene la propiedad 'database_name'.");

                _dbContext.CurrentDb = request.Schema.DatabaseName;

                var convertedData = ConvertJsonElementsToNetTypes(request.Data);

                var validatedData = ValidateAndMapData(convertedData, tableName, request.Schema);

                if (validatedData.Count == 0)
                    return BadRequest("No hay datos válidos para actualizar.");

                using (var connection = _connectionFactory.CreateConnection())
                {
                    var result = await _dynamicService.UpdateDynamicAsync(
                        tableName,
                        validatedData,
                        request.Schema,
                        connection.ConnectionString
                    );

                    return Ok(new { message = "Registro actualizado exitosamente", rowsAffected = result });
                }
            }
            catch (Exception ex)
            {
                return BadRequest(new { error = ex.Message });
            }
        }

        /// <summary>
        /// Returns all rows from the specified table using the schema provided in the request body.
        /// The schema must include a valid <c>database_name</c> property.
        /// </summary>
        /// <param name="tableName">Name of the target table.</param>
        /// <param name="request">Request payload containing the schema definition.</param>
        [HttpPost("V2/GETALL")]
        public async Task<IActionResult> GetALL(string tableName, [FromBody] DynamicRequestDto request)
        {
            try
            {
                if (request.Schema == null)
                    return BadRequest("El esquema es obligatorio.");

                if (string.IsNullOrEmpty(request.Schema.DatabaseName))
                    return BadRequest("El JSON del esquema no contiene la propiedad 'database_name'.");

                _dbContext.CurrentDb = request.Schema.DatabaseName;

                using (var connection = _connectionFactory.CreateConnection())
                {
                    var result = await _dynamicService.GetAllDynamicAsync(
                        tableName,
                        request.Schema,
                        connection.ConnectionString
                    );

                    return Ok(new { message = "Datos obtenidos exitosamente", rowsAffected = result });
                }
            }
            catch (Exception ex)
            {
                return BadRequest(new { error = ex.Message });
            }
        }

        /// <summary>
        /// Returns a single row from the specified table by its primary key value.
        /// The schema must include a valid <c>database_name</c> property.
        /// </summary>
        /// <param name="tableName">Name of the target table.</param>
        /// <param name="id">Primary key value of the row to retrieve.</param>
        /// <param name="schema">Schema definition for the target table.</param>
        [HttpPost("V2/GETBYID/{id}")]
        public async Task<IActionResult> GetById(string tableName, int id, [FromBody] DbSchema schema)
        {
            try
            {
                if (schema == null)
                    return BadRequest("El esquema es obligatorio.");

                if (string.IsNullOrEmpty(schema.DatabaseName))
                    return BadRequest("El JSON del esquema no contiene la propiedad 'database_name'.");

                _dbContext.CurrentDb = schema.DatabaseName;

                using (var connection = _connectionFactory.CreateConnection())
                {
                    var result = await _dynamicService.GetByIdDynamicAsync(
                        tableName,
                        id,
                        schema,
                        connection.ConnectionString
                    );

                    if (result == null)
                        return NotFound(new { message = "Registro no encontrado" });

                    return Ok(result);
                }
            }
            catch (Exception ex)
            {
                return BadRequest(new { error = ex.Message });
            }
        }
    }
}
